sudo: required

language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
    
services:
  - docker

before_install
  - docker build -t wailamy/DockerTest -f Dockerfile.dev . 

script:
  - docker run -e CI=true wailamy/DockerTest npm run test
  