sudo: required

language: node_js

node_js:
  - 8
    
services:
  - docker

before_install:
  - docker build -t raynoryip/dockertest -f Dockerfile.dev . 

cache:
  directories:
    - node_modules

script:
  - docker run -e CI=true raynoryip/dockertest npm run test
  